### ISSUE TITLE
Writing () moves cursor unexpectedly

### ISSUE THREAD

**Issue by deekej** [honza/vim-snippets#1171]
Hello guys,

I was debugging strange behaviour in my VIM configuration, and eventually found out that with vim-snippets enabled, writing parenthesis `()` will move the cursor before the parenthesis (instead of keeping it behind it) [in Insert mode].

After disabling the `vim-snippets` plugin in Vundle, the VIM behaves as expected. If you need my configuration for reproduction, I will have it for you soon (I'm in the middle of creating my own repository with my config). :)

Dee'Kej

**Comment by lpil** [comment]
Hiya! There was a bug previously but I think it was fixed. Could you double check you're using the latest version of this repo? Thanks

**Comment by deekej** [comment]
Hello @lpil, I just updated all the plugins with Vundle, enabled the vim-snippets plugin, and tested it again. Unfortunately, the issue still persists.

Here's my current VIM configuration: https://github.com/deekej/vim-ultimate-IDE

If you want to test it yourself, make sure to uncomment line 46 to enable plugin 'honza/vim-snippets'. :)

**Comment by lpil** [comment]
I've been unable to replicate this. Are you sure you're on the latest version? The snippets in question were removed from the repo a month ago https://github.com/honza/vim-snippets/pull/1155/files

**Comment by deekej** [comment]
> I've been unable to replicate this. Are you sure you're on the latest version? The snippets in question were removed from the repo a month ago d4d0a18

You're right actually, it was really fixed. After manually issuing `git pull` for this repo I no longer have the issue. For some reason Vundle didn't update the plugin correctly. Or more probably I've messed up somewhere else... :-/ Sorry for the noise. And thanks!

**Comment by lpil** [comment]
Glad we got to the bottom of this! Cheers :)
