### ISSUE TITLE
Reduce similarly-triggered snippets for Elixir

### ISSUE THREAD

**Issue by benhamill** [honza/vim-snippets#556]
So I noticed that there's a number of `if` snippets in the Ultisnips Elixir snippets. This means that if you type `if<tab>`, you then have to hit a number every time. I was wondering if I could make that less of a thing.

As best I can tell, there are 4 cases that need covering:

```elixir
if condition do
  expression
end

if condition do
  expression
else
  other_expression
end

if condition, do: expression

if condition, do: expression, else: other_expression
```

Right now, they each have their own snippet: two trigger on `if` and two on `ife`.

What if we changed it so that we had one snippet that triggered on `if` for the multi-line form and one that triggered on `if:` (of maybe `iff` or something better?) and used Ultisnips's optional tabstop feature to handle the differences given by `else`? The same could go for `unless` and I think the various `def`-related snippets could be simplified by use of the optional tabstop feature.

There are a couple of whitespace related things that I think bear cleaning up...

Before I format it all nicely and make a bunch of edits... is this the kind of PR that would be appreciated and reviewed, etc. or am I off on some wild track, right now?

**Comment by lpil** [comment]
Hey!

Great minds think alike- I fixed this [back in February](https://github.com/honza/vim-snippets/commit/d52befe8bc86fd0674c3b83236763157af31f8cf). If you update your plugin everything will be fine. :)

Feel free to make a PR for any other stuff.

**Comment by benhamill** [comment]
:facepalm: It's apparently amateur hour over here. :wink: Thanks. I'll pull and may still have some changes to suggest. Haha, bleh.

**Comment by benhamill** [comment]
@lpil: So it looks like, [also back in February](https://github.com/honza/vim-snippets/commit/1831acc72f47993539399c00e5c1f38ab8d1e482), you deleted the Ultisnips versions of the Elixir snippets. The commit message indicates you thought they were duplicates, but AFAIK, this project is meant to support Ultisnips's syntax in that directory and snipMate's in the other, so both are desirable.

IMO, they should be recreated. Do you want me to take a stab? I'm thinking I'd start by trying to cover the functionality in the snipMate file and then add any of the ones I've written that seem generally useful (which might also bear porting back into the snipMate file, if you like). Thoughts?

**Comment by benhamill** [comment]
I see, now, that it looks like Ultisnips fails over to the snipMate files. So, yeah... duplicates. I think some of them could be made more usable by using some of the Ultisnips-specific syntax. Is it cool to shadow them like that (I know it'll work, I'm asking about project culture)? Or should I make my own variations for me and leave the project alone? Sorry for all the notifications, if you're getting them.

**Comment by SirVer** [comment]
It is fine to add overwrites for ultisnips that shadow the snipMate ones as long as they use US features.

**Comment by lpil** [comment]
What @SirVer said.

No worries. Always happy to answer questions. :)
